FROM qmsk/pngtile.common

RUN apt-get update && apt-get install -y \
    uwsgi uwsgi uwsgi-plugin-python

RUN adduser --system --uid 1000 --home /srv/pngtile --group pngtile

USER pngtile
CMD uwsgi --ini /src/pngtile/python/tileserver.ini --http-socket :9090
EXPOSE 9090/tcp

VOLUME /srv/pngtile/images

ENV \
    QMSK_PNGTILE_PATH=/srv/pngtile/images \
    QMSK_PNGTILE_IMAGES_URL= \
